Feature/37 add archive rw class
sunnah-com/corrections pull request #52
Opened 2020-10-20 02:17 UTC by Ysajid

2020-10-20 18:13 UTC, hasankhan commented
JazakAllah khair. Can you kindly pull/merge the latest code and resolve conflicts and squash the commits?

2020-10-22 02:50 UTC, hasankhan requested changes
can you check why test is failing?

2020-10-22 02:50 UTC, hasankhan commented on frontend/.env.local.sample
> +DYNAMODB_ENDPOINT_URL=http://dynamodb-local:8000/
can we revert this please?

2020-10-22 02:50 UTC, hasankhan commented on frontend/conftest.py
> +        table = dynamodb.create_table(
we can use init script that we already have instead of creating a table in the test. We can assume table exists.

2020-10-22 02:50 UTC, hasankhan commented on frontend/tests/factories.py
> +def dynamodb_factory(endpoint_url: str, region: str = None):
why are we using this factory? It is not hiding much complexity it seems.

2020-10-24 00:36 UTC, Ysajid commented on frontend/.env.local.sample
> +DYNAMODB_ENDPOINT_URL=http://dynamodb-local:8000/
reverted

2020-10-24 00:37 UTC, Ysajid commented
Brother @hasankhan this PR is updated, please have a look when u can.

2020-10-24 07:22 UTC, merged

2020-10-24 07:22 UTC, hasankhan commented
JazakAllah khair